name: Daily Contest Bot

on:
  schedule:
    # 12:30 UTC is 06:00 PM IST
    - cron: '30 12 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CLIST_USERNAME: ${{ secrets.CLIST_USERNAME }}
          CLIST_API_KEY: ${{ secrets.CLIST_API_KEY }}
        run: python main.py